exp_name: "mj_add_gaussian"
seed: 1024

data:
  batch_size: 8
  num_workers: 8
  data_dir: '../data'
  model_dir: './trained_models'
  image_size: 2048
  input_size: 1024
  save_interval: 50

wandb:
  project_name: 'OCR_receipt'

solver:
  max_epoch: 150
  lr: 0.001

transform:
  transform_type: albumentations
  augmentations:
    - type: HorizontalFlip
      params:
        p: 0.5
    - type: Rotate
      params:
        limit: 30
        p: 0.7
    - type: RandomBrightnessContrast
      params:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.5