exp_name: "ES_maksing_transcription"
seed: 1024

data:
  batch_size: 8
  num_workers: 8
  data_dir: './data'
  model_dir: './trained_models'
  image_size: 2048
  input_size: 1024
  save_interval: 10

wandb:
  project_name: 'OCR_receipt'

solver:
  max_epoch: 250
  lr: 0.001

